server:
  port: 11334

spring:
  application:
    name: order-service

  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/modong?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: root
        password: admin

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
    devtools:
      livereload:
        enabled: true
